// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvinceCity.Data;

#nullable disable

namespace ProvinceCity.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceCode");

                    b.ToTable("City", (string)null);

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Sven",
                            Population = 3,
                            ProvinceCode = "CA"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Hendrik",
                            Population = 3,
                            ProvinceCode = "CA"
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "John",
                            Population = 3,
                            ProvinceCode = "CA"
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Sven",
                            Population = 3,
                            ProvinceCode = "BC"
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Hendrik",
                            Population = 3,
                            ProvinceCode = "BC"
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "John",
                            Population = 3,
                            ProvinceCode = "BC"
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "Sven",
                            Population = 3,
                            ProvinceCode = "AB"
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Hendrik",
                            Population = 3,
                            ProvinceCode = "AB"
                        },
                        new
                        {
                            CityId = 9,
                            CityName = "John",
                            Population = 3,
                            ProvinceCode = "AB"
                        });
                });

            modelBuilder.Entity("Province", b =>
                {
                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceCode");

                    b.ToTable("Province", (string)null);

                    b.HasData(
                        new
                        {
                            ProvinceCode = "BC",
                            ProvinceName = "Canucks"
                        },
                        new
                        {
                            ProvinceCode = "CA",
                            ProvinceName = "Sharks"
                        },
                        new
                        {
                            ProvinceCode = "AB",
                            ProvinceName = "Oilers"
                        });
                });

            modelBuilder.Entity("City", b =>
                {
                    b.HasOne("Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceCode");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Province", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
